---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: apt
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: tarball
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true    
provisioner:
  name: ansible
  inventory:
    host_vars:
      apt:
        mattermost_install_type: "apt"
      tarball:
        mattermost_install_type: "tarball"
verifier:
  name: ansible
